# Generated by Django 4.1.3 on 2022-12-01 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of jewellery category', max_length=80, verbose_name='category name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='MetalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metal_type', models.CharField(max_length=30, verbose_name='metal type')),
            ],
            options={
                'ordering': ['metal_type'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('n', 'new - not approved'), ('a', 'advance payment taken - approved'), ('d', 'design stage'), ('m', 'manufacturing stage'), ('d', 'done but not picked up'), ('p', 'done and picked up'), ('c', 'cancelled'), ('f', 'fully paid')], default='n', max_length=1, verbose_name='status')),
                ('date', models.DateField(auto_now_add=True, verbose_name='order date')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='total amount')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jewellery.customer', verbose_name='customer')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='product name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='product price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='product image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='jewellery.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=2000, verbose_name='review content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='jewellery.product', verbose_name='product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='unique ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='price')),
                ('hand', models.CharField(blank=True, choices=[('r', 'right'), ('l', 'left')], max_length=1, null=True, verbose_name='hand')),
                ('finger', models.CharField(blank=True, choices=[('t', 'thumb'), ('i', 'index'), ('m', 'middle'), ('r', 'ring'), ('p', 'pinky')], max_length=1, null=True, verbose_name='finger')),
                ('ring_size', models.CharField(blank=True, max_length=20, null=True, verbose_name='ring_size')),
                ('measurement', models.CharField(blank=True, max_length=200, null=True, verbose_name='measurement')),
                ('weight', models.CharField(blank=True, max_length=200, null=True, verbose_name='weight')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product_photos', verbose_name='photo')),
                ('specification', models.TextField(blank=True, help_text='Enter preferred specifications for this product', max_length=2000, null=True, verbose_name='specification')),
                ('engraving', tinymce.models.HTMLField(blank=True, max_length=150, null=True, verbose_name='engraving text')),
                ('engraving_file', models.ImageField(blank=True, null=True, upload_to='engraving_files', verbose_name='engraving file')),
                ('metal_type', models.ManyToManyField(to='jewellery.metaltype', verbose_name='metal type(s)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='jewellery.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='jewellery.product', verbose_name='product')),
            ],
        ),
    ]
