# Generated by Django 4.1.3 on 2022-12-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0003_pearl_alter_metaltype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pearl',
            options={'ordering': ['shape']},
        ),
        migrations.AlterField(
            model_name='pearl',
            name='type_name',
            field=models.CharField(max_length=30, verbose_name='type name'),
        ),
    ]
