# Generated by Django 4.1.3 on 2022-12-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0005_alter_order_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='pearl',
            field=models.ManyToManyField(blank=True, to='jewellery.pearl', verbose_name='pearl(s)'),
        ),
    ]
