# Generated by Django 4.1.3 on 2022-12-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0006_alter_orderline_pearl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='engraving',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='engraving text'),
        ),
    ]
