# Generated by Django 4.1.3 on 2022-12-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0007_alter_orderline_engraving'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='certificate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='certificate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('n', 'new - not approved'), ('a', 'advance payment taken - approved'), ('b', 'design stage'), ('m', 'manufacturing stage'), ('d', 'done but not picked up'), ('p', 'done and picked up'), ('c', 'cancelled'), ('f', 'fully paid')], default='n', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='engraving_file',
            field=models.FileField(blank=True, null=True, upload_to='engraving_files', verbose_name='engraving file'),
        ),
    ]
