# Generated by Django 4.1.3 on 2022-12-09 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0008_orderline_certificate_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelleryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of jewellery type', max_length=80, verbose_name='jewellery type')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='jewellery_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jewellery.jewellerytype', verbose_name='jewellery type'),
        ),
    ]
