# Generated by Django 4.1.3 on 2022-12-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewellery', '0009_jewellerytype_product_jewellery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='restoration',
            field=models.DateField(blank=True, null=True, verbose_name='restoration date'),
        ),
    ]
